# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Database": "05_database.ipynb",
         "Scrapper": "10_scrapper_get_tweet.ipynb",
         "scrapper": "10_scrapper_get_tweet.ipynb"}

modules = ["database.py",
           "scrapper.py"]

doc_url = "https://leximpact.github.io/tweet-archiveur/"

git_url = "https://github.com/leximpact/tweet-archiveur/tree/main/"

def custom_doc_links(name): return None
